### ISSUE TITLE
Better geolocation handling

### ISSUE THREAD

**Issue by arjun27** [arjun27/covid-maps#1]
quick notes on geolocation

- ideally we should not prompt for location permissions when the app is launched
  - make that more explicit
- speed up map load? seems to be stuck if the current location is not available
- ~race condition in updating map's center~ fixed!

**Comment by arjun27** [comment]
It seems iOS messenger doesn’t even ask for geo permissions. Need to fix that as well.

**Comment by asanjeevrao** [comment]
On Messenger, it asks for location permission on each page - need to fix this

**Comment by sampoorna** [comment]
What's the desired behaviour here? We want it to prompt? Or not prompt?

**Comment by arjun27** [comment]
my opinion (open to debate)
- by default, use the IP address of the user and get a rough location through ipinfo.io (this does not require any permissions)
- have a button or something that user can tap to get a more accurate location
  - when they tap it, prompt for permissions

**Comment by phanikishn** [comment]
If you are planning to run this in India as part of MVP we could just take the location access. People will give it quite willingly. I'm not sure if the location through IP address will be accurate enough.

**Comment by arjun27** [comment]
We will definitely go with the geolocation access route. Currently we ask for geolocation as the very first thing, and if someone denies access, the app doesn’t work at all.

Having a way to give access later on will be useful in my opinion. What do you think?

**Comment by phanikishn** [comment]
Yes - but in MVP we can skip? We are going for high intent use-cases IMO. Maybe cultural context is important - most Indians wouldn't care about the permissions they give but might not be true of others.
