### ISSUE TITLE
Set up the location input fields

### ISSUE THREAD

**Issue by arjun27** [arjun27/covid-maps#2]
in the form, inputting the text fields is fairly simple to do. getting location input needs more work, but is critical for easy and location relevant data entry.

- we have the current location thing hooked up
- we want to have a location / address field which is powered by google maps suggestions
   - the map and the location input field should be in sync
   - this would require some react work + google maps API integration

**Comment by asanjeevrao** [comment]
I found some documentation on this - https://medium.com/@hamzaqaisrani/using-the-google-maps-places-autocomplete-javascript-api-in-a-react-project-5742bab4abc9

**Comment by arjun27** [comment]
nice that's exactly what we want I think. want to try building it out?

**Comment by phanikishn** [comment]
We discussed this on call - I think we should pre-populate the home screen with stale but accurate info. Basically on opening the app I just see "popular" stores around me. We could color code them - red (closed), yellow (don't know status), green (is open) or something like that.

If it's through search, google maps places api should be able to help but I don't know if consumer will necessarily know the name of a place given more often than not people buy in Kirana store and not a super market. If consumer doesn't know the name of the place, what do we do?
